---
abstract: 'A multi-purpose subroutine wrapping framework'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-Wrapper
requires:
  Data::Clone: 0
  Data::Sah: 0.14
  Log::Any: 0
  Perinci::Sub::DepChecker: 0.06
  Perinci::Sub::Util: 0
  Rinci: v1.1.36
  SHARYANTO::String::Util: 0.22
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Perinci-Sub-Wrapper/
  repository: http://github.com/sharyanto/perl-Perinci-Sub-Wrapper
version: 0.47
